<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <title>Sign In</title>
  <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@400;600&display=swap" rel="stylesheet">
  <style>
    body {
      margin: 0;
      font-family: 'Kanit', sans-serif;
      background-color: #2c1d5b;
      color: white;
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
    }

    .signin-container {
      background-color: #3b2b6d;
      padding: 30px 25px;
      border-radius: 12px;
      width: 100%;
      max-width: 400px;
      box-shadow: 0 0 15px rgba(0,0,0,0.3);
      border: 1px solid #ffffff33;
    }

    .signin-container h2 {
      text-align: center;
      margin-bottom: 25px;
      color: #f9d423;
    }

    .signin-container label {
      display: block;
      margin-bottom: 6px;
      font-weight: 600;
    }

    .signin-container input {
      width: 100%;
      padding: 10px;
      margin-bottom: 18px;
      border: none;
      border-radius: 6px;
      background-color: #2c1d5b;
      color: white;
      font-size: 14px;
    }

    .signin-container input:focus {
      outline: none;
      border: 1px solid #f9d423;
      background-color: #342662;
    }

    .signin-container button {
      width: 100%;
      padding: 12px;
      background-color: #f9d423;
      color: #2c1d5b;
      font-weight: 600;
      border: none;
      border-radius: 6px;
      font-size: 16px;
      cursor: pointer;
      transition: background-color 0.3s;
    }

    .signin-container button:hover {
      background-color: #ffcc00;
    }

    .signin-container .signup-link {
      text-align: center;
      margin-top: 16px;
      font-size: 14px;
    }

    .signin-container .signup-link a {
      color: #f9d423;
      text-decoration: none;
    }

    .signin-container .signup-link a:hover {
      text-decoration: underline;
    }
  </style>
</head>
<body>

  <div class="signin-container">
    <h2>Sign In</h2>
    <form action="process_signin.php" method="POST">
      <label for="email">Email</label>
      <input type="email" name="email" id="email" required>

      <label for="password">Password</label>
      <input type="password" name="password" id="password" required>

      <button type="submit">Login</button>

      <div class="signup-link">
        Don’t have an account? <a href="signup.php">Create One</a>
      </div>
    </form>
  </div>

</body>
</html># This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
